import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";
import { Inter } from 'next/font/google';
import type { Metadata } from "next";
import { Theme } from '@radix-ui/themes'
import NavBar from "./Navbar/NavBar";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "App Router Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="bronze" radius="small">
            <NavBar />
          <main className="p-4">
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
